language: node_js

node_js:
  - "6"

install:
  - npm install

before_script:
  - npm install -g gulp-cli

script: gulp deploy

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
